# Title

In [1]:
%config InteractiveShell.ast_node_interactivity='last_expr_or_assign'  # always print last expr.
%config InlineBackend.figure_format = 'svg'
%load_ext autoreload
%autoreload 2
%matplotlib inline

In [34]:
import torch
from torch.utils.data import DataLoader, TensorDataset, ConcatDataset

datasets = []
for i in range(3):
    datasets.append(TensorDataset(torch.randn(2+i), torch.randn(2+i,5)))
    display(datasets[i].tensors)

(tensor([0.5204, 0.2580]),
 tensor([[-0.2021,  0.8695,  0.2856, -1.0662, -1.3433],
         [ 0.3149,  0.8971,  1.2549,  0.2300,  0.7925]]))

(tensor([ 0.8646,  0.8771, -0.8943]),
 tensor([[ 1.8768,  0.3980, -0.6414, -0.0858,  0.4588],
         [ 1.0035,  1.3665, -0.6715,  0.7834, -0.2403],
         [-0.1152, -1.7330,  0.1195, -0.2587,  1.2134]]))

(tensor([ 1.5049, -0.5286,  0.4686, -0.6155]),
 tensor([[-1.2486, -1.4926,  0.0074,  0.7650,  0.0159],
         [ 1.5618, -1.6210, -3.0358,  0.0814,  0.0486],
         [ 0.0446, -0.9060,  0.4613,  0.8977, -1.3056],
         [ 0.4153,  1.1805,  0.0445,  1.1187,  0.6177]]))

In [35]:
dataset = ConcatDataset(datasets)
dloader = DataLoader(
    dataset,
    shuffle=False,
    num_workers=0,
    batch_size=3
)

In [36]:
for batch in dloader:
    display(batch)
    print(batch[0].shape, batch[1].shape)

[tensor([0.5204, 0.2580, 0.8646]),
 tensor([[-0.2021,  0.8695,  0.2856, -1.0662, -1.3433],
         [ 0.3149,  0.8971,  1.2549,  0.2300,  0.7925],
         [ 1.8768,  0.3980, -0.6414, -0.0858,  0.4588]])]

torch.Size([3]) torch.Size([3, 5])


[tensor([ 0.8771, -0.8943,  1.5049]),
 tensor([[ 1.0035,  1.3665, -0.6715,  0.7834, -0.2403],
         [-0.1152, -1.7330,  0.1195, -0.2587,  1.2134],
         [-1.2486, -1.4926,  0.0074,  0.7650,  0.0159]])]

torch.Size([3]) torch.Size([3, 5])


[tensor([-0.5286,  0.4686, -0.6155]),
 tensor([[ 1.5618, -1.6210, -3.0358,  0.0814,  0.0486],
         [ 0.0446, -0.9060,  0.4613,  0.8977, -1.3056],
         [ 0.4153,  1.1805,  0.0445,  1.1187,  0.6177]])]

torch.Size([3]) torch.Size([3, 5])
