# What are TensorDataset and ConcatDataset doing?

In [1]:
%config InteractiveShell.ast_node_interactivity='last_expr_or_assign'  # always print last expr.
%config InlineBackend.figure_format = 'svg'
%load_ext autoreload
%autoreload 2
%matplotlib inline

Create a list of TensorDatasets

- each TensorDataset has same modality, but different number of instances

In [42]:
import torch
from torch.utils.data import DataLoader, TensorDataset, ConcatDataset

datasets = [
    TensorDataset(torch.randn(5), torch.randn(5, 3)),
    TensorDataset(torch.randn(7), torch.randn(7, 3)),
    TensorDataset(torch.randn(8), torch.randn(8, 3)),
]
dataset = ConcatDataset(datasets)

In [43]:
dloader = DataLoader(
    dataset, shuffle=True, num_workers=0, batch_size=3, drop_last=False
)
for batch in dloader:
    print(type(batch), len(batch), [tuple(x.shape) for x in batch])

<class 'list'> 2 [(3,), (3, 3)]
<class 'list'> 2 [(3,), (3, 3)]
<class 'list'> 2 [(3,), (3, 3)]
<class 'list'> 2 [(3,), (3, 3)]
<class 'list'> 2 [(3,), (3, 3)]
<class 'list'> 2 [(3,), (3, 3)]
<class 'list'> 2 [(2,), (2, 3)]


### Q: How do the items get selected?

In [52]:
for ds in datasets:
    print("\nDATASET\n", ds[:])


DATASET
 (tensor([-0.5993, -0.4146,  0.6018, -0.7173, -0.7705]), tensor([[-0.8289,  0.8738,  0.2192],
        [ 0.3662, -0.8214,  0.0166],
        [-0.1531,  0.1577, -1.3896],
        [-0.8381,  0.0381,  0.5665],
        [ 0.1461,  0.0096,  0.4294]]))

DATASET
 (tensor([ 1.1492,  0.2060,  2.3548,  0.3277, -1.4562, -0.0383,  0.9278]), tensor([[-0.7674,  1.3792,  1.6851],
        [ 1.1168,  0.5224,  1.9434],
        [-1.3515, -2.4870, -0.9593],
        [-1.6961,  0.5043, -0.4329],
        [-0.6224, -0.0500,  0.2175],
        [-1.2546,  0.8213, -1.1129],
        [-0.6852, -0.6457, -0.3346]]))

DATASET
 (tensor([ 0.7741,  0.5806, -0.0964, -2.2165, -0.6764, -0.1525,  1.5026,  0.3429]), tensor([[ 1.2128, -0.1223,  0.0990],
        [ 0.0199, -1.4841, -0.7044],
        [-1.0134,  0.5308,  0.8318],
        [-1.1538,  0.2334, -0.5244],
        [ 0.4320, -1.9613, -0.1311],
        [ 0.0043,  0.8035,  0.7869],
        [ 1.1299, -0.1088, -0.2635],
        [ 0.4861,  1.7904, -0.2606]]))


In [55]:
for item in dataset:
    print(item)

(tensor(-0.5993), tensor([-0.8289,  0.8738,  0.2192]))
(tensor(-0.4146), tensor([ 0.3662, -0.8214,  0.0166]))
(tensor(0.6018), tensor([-0.1531,  0.1577, -1.3896]))
(tensor(-0.7173), tensor([-0.8381,  0.0381,  0.5665]))
(tensor(-0.7705), tensor([0.1461, 0.0096, 0.4294]))
(tensor(1.1492), tensor([-0.7674,  1.3792,  1.6851]))
(tensor(0.2060), tensor([1.1168, 0.5224, 1.9434]))
(tensor(2.3548), tensor([-1.3515, -2.4870, -0.9593]))
(tensor(0.3277), tensor([-1.6961,  0.5043, -0.4329]))
(tensor(-1.4562), tensor([-0.6224, -0.0500,  0.2175]))
(tensor(-0.0383), tensor([-1.2546,  0.8213, -1.1129]))
(tensor(0.9278), tensor([-0.6852, -0.6457, -0.3346]))
(tensor(0.7741), tensor([ 1.2128, -0.1223,  0.0990]))
(tensor(0.5806), tensor([ 0.0199, -1.4841, -0.7044]))
(tensor(-0.0964), tensor([-1.0134,  0.5308,  0.8318]))
(tensor(-2.2165), tensor([-1.1538,  0.2334, -0.5244]))
(tensor(-0.6764), tensor([ 0.4320, -1.9613, -0.1311]))
(tensor(-0.1525), tensor([0.0043, 0.8035, 0.7869]))
(tensor(1.5026), tensor([ 1

## So, as the name suggests, the datasets simply get concatenated!!

## Different Modalities ⟹ Not well supported!

In [38]:
dloader = DataLoader(dataset, shuffle=True, num_workers=0, batch_size=3)
for batch in dloader:
    print(type(batch), len(batch), [tuple(x.shape) for x in batch])

<class 'list'> 2 [(3,), (3, 3)]
<class 'list'> 2 [(3,), (3, 3)]
<class 'list'> 2 [(3,), (3, 3)]
<class 'list'> 2 [(3,), (3, 3)]
<class 'list'> 2 [(3,), (3, 3)]
<class 'list'> 2 [(3,), (3, 3)]
<class 'list'> 2 [(3,), (3, 3)]
