In [1]:
import torch
from torch.utils.data import Dataset, DataLoader
import numpy as np
from torch import Tensor
from torch.nn.utils.rnn import pack_sequence, pad_sequence, pack_padded_sequence, pad_packed_sequence, PackedSequence

In [2]:
class VaryingLengthDataset(Dataset):
    def __init__(self, n, dmin, dmax):
        super().__init__()
        self.size = n
        self.data = [torch.randint(0, 10, (np.random.randint(dmin, dmax), 2)) for _ in range(n)]
        
    # a commemt
    def __len__(self):
        return self.size
    
    def __getitem__(self, index):
        return self.data[index]
    
    def __repr__(self):
        return "".join(repr(x.shape) for x in self.data)
    
def myfun():
    pass

In [86]:
start = pandas.Timestamp("today")
stop = now + pandas.Timedelta("24h")
freq = pandas.Timedelta("1s")

In [2]:
import tsdm

In [128]:
np.insert?

Signature: np.insert(arr, obj, values, axis=None)
Docstring:
Insert values along the given axis before the given indices.

Parameters
----------
arr : array_like
    Input array.
obj : int, slice or sequence of ints
    Object that defines the index or indices before which `values` is
    inserted.

    .. versionadded:: 1.8.0

    Support for multiple insertions when `obj` is a single scalar or a
    sequence with one element (similar to calling insert multiple
    times).
values : array_like
    Values to insert into `arr`. If the type of `values` is different
    from that of `arr`, `values` is converted to the type of `arr`.
    `values` should be shaped so that ``arr[...,obj,...] = values``
    is legal.
axis : int, optional
    Axis along which to insert `values`.  If `axis` is None then `arr`
    is flattened first.

Returns
-------
out : ndarray
    A copy of `arr` with `values` inserted.  Note that `insert`
    does not occur in-place: a new array is returned. If
    `axis` is

In [112]:
rng = np.random.default_rng()
timestamps = rng.choice(time_range, 10)

In [104]:
Timestamp(datetime.datetime(1950, 1, 1))

Timestamp('1950-01-01 00:00:00')

In [110]:
np.random.shuffle

<function RandomState.shuffle>

In [100]:
import datetime

In [112]:
type(datetime.timedelta(seconds=3))

datetime.timedelta

In [113]:
issubclass(np.timedelta64, datetime.timedelta)

False

In [108]:
np.array(datetime.timedelta(seconds=5), dtype="timedelta64[s]").dtype

dtype('<m8[s]')

In [75]:
dsets = []

for key, val in InSilicoData.dataset.items():
    ds = df.to_xarray()
    ds = ds.assign_coords(run_id = key)
    dsets.append(ds)

In [77]:
dsets

[<xarray.Dataset>
 Dimensions:    (time: 652)
 Coordinates:
   * time       (time) datetime64[ns] 2021-06-28T09:41:57 ... 2021-06-28T21:31:57
     run_id     <U9 'run_16130'
 Data variables:
     Biomass    (time) float64 nan nan nan nan nan nan ... nan nan nan nan nan
     Substrate  (time) float64 nan nan nan nan nan nan ... nan nan nan nan nan
     Acetate    (time) float64 nan nan nan nan nan nan ... nan nan nan nan nan
     DOTm       (time) float64 nan 0.9839 1.0 0.9864 0.9742 ... nan nan nan nan
     Product    (time) float64 nan nan nan nan nan nan ... nan nan nan nan nan
     Volume     (time) float64 0.01 nan nan nan nan ... 0.009797 0.00981 nan nan
     Feed       (time) float64 0.0 0.0 0.0 0.0 ... 2.185e-05 2.185e-05 2.185e-05,
 <xarray.Dataset>
 Dimensions:    (time: 652)
 Coordinates:
   * time       (time) datetime64[ns] 2021-06-28T09:41:57 ... 2021-06-28T21:31:57
     run_id     <U9 'run_16131'
 Data variables:
     Biomass    (time) float64 nan nan nan nan nan nan ... 

In [96]:
np.datetime64?

Init signature: np.datetime64(self, /, *args, **kwargs)
Docstring:     
If created from a 64-bit integer, it represents an offset from
``1970-01-01T00:00:00``.
If created from string, the string can be in ISO 8601 date
or datetime format.

>>> np.datetime64(10, 'Y')
numpy.datetime64('1980')
>>> np.datetime64('1980', 'Y')
numpy.datetime64('1980')   
>>> np.datetime64(10, 'D')
numpy.datetime64('1970-01-11')

See :ref:`arrays.datetime` for more information.

:Character code: ``'M'``
File:           ~/miniconda3/envs/kiwi/lib/python3.9/site-packages/numpy/__init__.py
Type:           type
Subclasses:     


In [91]:
import numpy as np
np.datetime64('now')

numpy.datetime64('2021-08-11T11:01:52')

In [95]:
np.datetime64(24, 'h')

numpy.datetime64('1970-01-02T00','h')

In [84]:
xarray.concat(dsets, dim="run_id").to_dataframe()

Biomass  Substrate  Acetate  DOTm  Product  \
time                run_id                                                  
2021-06-28 09:41:57 run_16130      NaN        NaN      NaN   NaN      NaN   
                    run_16131      NaN        NaN      NaN   NaN      NaN   
                    run_16132      NaN        NaN      NaN   NaN      NaN   
                    run_16133      NaN        NaN      NaN   NaN      NaN   
                    run_16134      NaN        NaN      NaN   NaN      NaN   
...                                ...        ...      ...   ...      ...   
2021-06-28 21:31:57 run_16133      NaN        NaN      NaN   NaN      NaN   
                    run_16134      NaN        NaN      NaN   NaN      NaN   
                    run_16135      NaN        NaN      NaN   NaN      NaN   
                    run_16136      NaN        NaN      NaN   NaN      NaN   
                    run_16137      NaN        NaN      NaN   NaN      NaN   

                               Volume      Feed  
time                run_id                       
2021-06-28 09:41:57 run_16130    0.01  0.000000  
                    run_16131    0.01  0.000000  
                    run_16132    0.01  0.000000  
                    run_16133    0.01  0.000000  
                    run_16134    0.01  0.000000  
...                               ...       ...  
2021-06-28 21:31:57 run_16133     NaN  0.000022  
                    run_16134     NaN  0.000022  
                    run_16135     NaN  0.000022  
                    run_16136     NaN  0.000022  
                    run_16137     NaN  0.000022  

[5216 rows x 7 columns]

In [38]:
arrays = [xarray.DataArray(df, name=key) for key, df in InSilicoData.dataset.items()  ]

In [67]:
arrays[0]

<xarray.DataArray 'run_16130' (time: 652, dim_1: 7)>
array([[           nan,            nan,            nan, ...,
                   nan, 1.00000000e-02, 0.00000000e+00],
       [           nan,            nan,            nan, ...,
                   nan,            nan, 0.00000000e+00],
       [           nan,            nan,            nan, ...,
                   nan,            nan, 0.00000000e+00],
       ...,
       [           nan,            nan,            nan, ...,
                   nan, 9.81012524e-03, 2.18524748e-05],
       [           nan,            nan,            nan, ...,
                   nan,            nan, 2.18524748e-05],
       [           nan,            nan,            nan, ...,
                   nan,            nan, 2.18524748e-05]])
Coordinates:
  * time     (time) datetime64[ns] 2021-06-28T09:41:57 ... 2021-06-28T21:31:57
  * dim_1    (dim_1) object 'Biomass' 'Substrate' 'Acetate' ... 'Volume' 'Feed'

In [40]:
xarray.merge( arrays)

<xarray.Dataset>
Dimensions:    (time: 658, dim_1: 7)
Coordinates:
  * time       (time) datetime64[ns] 2021-06-28T09:41:57 ... 2021-06-28T21:31:57
  * dim_1      (dim_1) object 'Biomass' 'Substrate' ... 'Volume' 'Feed'
Data variables:
    run_16130  (time, dim_1) float64 nan nan nan nan ... nan nan nan 2.185e-05
    run_16131  (time, dim_1) float64 nan nan nan nan ... nan nan nan 2.174e-05
    run_16132  (time, dim_1) float64 nan nan nan nan ... nan nan nan 2.144e-05
    run_16133  (time, dim_1) float64 nan nan nan nan ... nan nan nan 2.144e-05
    run_16134  (time, dim_1) float64 nan nan nan nan ... nan nan nan 2.189e-05
    run_16135  (time, dim_1) float64 nan nan nan nan ... nan nan nan 2.174e-05
    run_16136  (time, dim_1) float64 nan nan nan nan ... nan nan nan 2.281e-05
    run_16137  (time, dim_1) float64 nan nan nan nan ... nan nan nan 2.131e-05

In [50]:
df = list(InSilicoData.dataset.values())[0]
df.name = "agagaga"

In [26]:
xarray.Dataset.from_dict(InSilicoData.dataset)

ValueError: cannot convert dict without the key 'dims'

In [19]:
dir(VaryingLengthDataset)

['__add__',
 '__class__',
 '__class_getitem__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__len__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__orig_bases__',
 '__parameters__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__slots__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_is_protocol']

### Batching this Dataset won't work:

In [3]:
MyDataset = VaryingLengthDataset(100, 3, 7)

try:
    next(iter(DataLoader(MyDataset, batch_size=10)))
    print(x)
except Exception as E:
    print(E)

stack expects each tensor to be equal size, but got [3, 2] at entry 0 and [5, 2] at entry 1


### Let's try with a custom collate_fn

In [4]:
np.random.randint(0, len(MyDataset), 20)

array([33, 23,  6, 29, 94, 44,  0, 21, 52, 36,  8, 14, 77, 84, 45, 74, 84,
       35, 69, 15])

In [5]:
batch = [MyDataset[idx] for idx in np.random.randint(0, len(MyDataset), 5)]
batch

[tensor([[2, 1],
         [5, 7],
         [9, 9],
         [5, 1]]),
 tensor([[1, 1],
         [7, 2],
         [4, 3]]),
 tensor([[2, 0],
         [3, 2],
         [6, 2],
         [1, 1]]),
 tensor([[8, 4],
         [5, 4],
         [8, 2],
         [0, 9],
         [4, 9]]),
 tensor([[1, 0],
         [2, 6],
         [1, 0],
         [0, 3],
         [3, 8]])]

In [6]:
pad_sequence(batch, batch_first=True).shape

torch.Size([5, 5, 2])

In [7]:
def collate_list(batch):
    return batch

try:
    x = next(iter(DataLoader(MyDataset, batch_size=5, collate_fn=collate_list)))
    print(x)
except Exception as E:
    print(E)

[tensor([[6, 5],
        [8, 0],
        [2, 5]]), tensor([[9, 9],
        [9, 1],
        [8, 6],
        [1, 4],
        [7, 0]]), tensor([[3, 6],
        [7, 3],
        [2, 9],
        [5, 3],
        [5, 5],
        [6, 5]]), tensor([[3, 2],
        [2, 5],
        [1, 9],
        [4, 2],
        [1, 7],
        [9, 2]]), tensor([[5, 6],
        [1, 0],
        [5, 5],
        [6, 1],
        [0, 8],
        [2, 0]])]


In [8]:
def collate_packed(batch):
    batch.sort(key=torch.Tensor.__len__, reverse=True)
    return pack_sequence(batch)

try:
    x = next(iter(DataLoader(MyDataset, batch_size=5, collate_fn=collate_packed)))
    print(x)
except Exception as E:
    print(E)

PackedSequence(data=tensor([[3, 6],
        [3, 2],
        [5, 6],
        [9, 9],
        [6, 5],
        [7, 3],
        [2, 5],
        [1, 0],
        [9, 1],
        [8, 0],
        [2, 9],
        [1, 9],
        [5, 5],
        [8, 6],
        [2, 5],
        [5, 3],
        [4, 2],
        [6, 1],
        [1, 4],
        [5, 5],
        [1, 7],
        [0, 8],
        [7, 0],
        [6, 5],
        [9, 2],
        [2, 0]]), batch_sizes=tensor([5, 5, 5, 4, 4, 3]), sorted_indices=None, unsorted_indices=None)


In [9]:
batch = next(iter(DataLoader(MyDataset, batch_size=5, collate_fn=collate_list)))
[x.T for x in batch]

[tensor([[6, 8, 2],
         [5, 0, 5]]),
 tensor([[9, 9, 8, 1, 7],
         [9, 1, 6, 4, 0]]),
 tensor([[3, 7, 2, 5, 5, 6],
         [6, 3, 9, 3, 5, 5]]),
 tensor([[3, 2, 1, 4, 1, 9],
         [2, 5, 9, 2, 7, 2]]),
 tensor([[5, 1, 5, 6, 0, 2],
         [6, 0, 5, 1, 8, 0]])]

In [10]:
batch_sorted = batch.copy()
batch_sorted.sort(key=torch.Tensor.__len__, reverse=True)
[x.T for x in batch_sorted]

[tensor([[3, 7, 2, 5, 5, 6],
         [6, 3, 9, 3, 5, 5]]),
 tensor([[3, 2, 1, 4, 1, 9],
         [2, 5, 9, 2, 7, 2]]),
 tensor([[5, 1, 5, 6, 0, 2],
         [6, 0, 5, 1, 8, 0]]),
 tensor([[9, 9, 8, 1, 7],
         [9, 1, 6, 4, 0]]),
 tensor([[6, 8, 2],
         [5, 0, 5]])]

In [11]:
batch_packed = pack_sequence(batch_sorted)
batch_packed.data.T, batch_packed.batch_sizes

(tensor([[3, 3, 5, 9, 6, 7, 2, 1, 9, 8, 2, 1, 5, 8, 2, 5, 4, 6, 1, 5, 1, 0, 7, 6,
          9, 2],
         [6, 2, 6, 9, 5, 3, 5, 0, 1, 0, 9, 9, 5, 6, 5, 3, 2, 1, 4, 5, 7, 8, 0, 5,
          2, 0]]),
 tensor([5, 5, 5, 4, 4, 3]))

In [12]:
batch_pad_packed, lengths = pad_packed_sequence(batch_packed, batch_first=True)
torch.swapaxes(batch_pad_packed, 1, 2), lengths

(tensor([[[3, 7, 2, 5, 5, 6],
          [6, 3, 9, 3, 5, 5]],
 
         [[3, 2, 1, 4, 1, 9],
          [2, 5, 9, 2, 7, 2]],
 
         [[5, 1, 5, 6, 0, 2],
          [6, 0, 5, 1, 8, 0]],
 
         [[9, 9, 8, 1, 7, 0],
          [9, 1, 6, 4, 0, 0]],
 
         [[6, 8, 2, 0, 0, 0],
          [5, 0, 5, 0, 0, 0]]]),
 tensor([6, 6, 6, 5, 3]))

In [13]:
unpacked_batch = [x[:l].T for x, l in zip(batch_pad_packed, lengths)]
unpacked_batch

[tensor([[3, 7, 2, 5, 5, 6],
         [6, 3, 9, 3, 5, 5]]),
 tensor([[3, 2, 1, 4, 1, 9],
         [2, 5, 9, 2, 7, 2]]),
 tensor([[5, 1, 5, 6, 0, 2],
         [6, 0, 5, 1, 8, 0]]),
 tensor([[9, 9, 8, 1, 7],
         [9, 1, 6, 4, 0]]),
 tensor([[6, 8, 2],
         [5, 0, 5]])]

In [14]:
def reconstruct_batch(packed: PackedSequence) -> list[Tensor]:
    d = packed.data.shape[-1]
    dtype = packed.data.dtype
    device = packed.data.device
    
    lengths = []
    b0 = 0
    for b in batch_sizes:
        
        lengths += [b]

In [15]:
reconstructed_batch = batch_pad_packed
reconstructed_batch

tensor([[[3, 6],
         [7, 3],
         [2, 9],
         [5, 3],
         [5, 5],
         [6, 5]],

        [[3, 2],
         [2, 5],
         [1, 9],
         [4, 2],
         [1, 7],
         [9, 2]],

        [[5, 6],
         [1, 0],
         [5, 5],
         [6, 1],
         [0, 8],
         [2, 0]],

        [[9, 9],
         [9, 1],
         [8, 6],
         [1, 4],
         [7, 0],
         [0, 0]],

        [[6, 5],
         [8, 0],
         [2, 5],
         [0, 0],
         [0, 0],
         [0, 0]]])

In [16]:
batch_pad_packed.shape

torch.Size([5, 6, 2])

In [17]:
def unpack(packed):
    pass

In [18]:
a = MyDataset[:5]
a.sort(key=lambda x: len(x))
a

[tensor([[6, 5],
         [8, 0],
         [2, 5]]),
 tensor([[9, 9],
         [9, 1],
         [8, 6],
         [1, 4],
         [7, 0]]),
 tensor([[3, 6],
         [7, 3],
         [2, 9],
         [5, 3],
         [5, 5],
         [6, 5]]),
 tensor([[3, 2],
         [2, 5],
         [1, 9],
         [4, 2],
         [1, 7],
         [9, 2]]),
 tensor([[5, 6],
         [1, 0],
         [5, 5],
         [6, 1],
         [0, 8],
         [2, 0]])]