In [2]:
%config InteractiveShell.ast_node_interactivity='last_expr_or_assign'  # always print last expr.
%config InlineBackend.figure_format = 'svg'
%load_ext autoreload
%autoreload 2

In [51]:
import torch
from torch.utils.data import Dataset, DataLoader
import numpy as np
from torch import Tensor
from torch.nn.utils.rnn import pack_sequence, pad_sequence, pack_padded_sequence, pad_packed_sequence, PackedSequence

In [52]:
import datetime
from typing import Final, Type, Union

import numpy as np
from numpy import datetime64, ndarray, timedelta64
from numpy.typing import ArrayLike, NDArray
import pandas
from pandas import Timedelta, Timestamp

TimeStampLike = Union[str, datetime.datetime, np.datetime64, pandas.Timestamp]
TimeDeltaLike = Union[str, datetime.timedelta, np.timedelta64, pandas.Timedelta]

typing.Union[str, datetime.timedelta, numpy.timedelta64, pandas._libs.tslibs.timedeltas.Timedelta]

In [53]:
a, b = False, True

In [49]:
Timedelta("900s")

Timedelta('0 days 00:15:00')

In [56]:
rng = np.random.default_rng()

rng.choice(np.arange(10), size=None)

2

In [43]:
np.arange(15)[a:-b or None]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [13]:
freq = Timedelta("15m")

Timedelta('0 days 00:15:00')

In [15]:
Timestamp("today")

Timestamp('2021-08-13 10:17:32.746254')

In [16]:
(Timestamp("today")+Timedelta("24h")).round(freq)

Timestamp('2021-08-14 10:15:00')

In [3]:
import tsdm

In [6]:
tsdm.random.timesamples(num=10, freq="15s")

array(['2021-08-13T10:14:44', '2021-08-13T11:22:44',
       '2021-08-13T14:02:59', '2021-08-13T18:58:14',
       '2021-08-13T21:51:44', '2021-08-13T22:09:14',
       '2021-08-13T22:24:14', '2021-08-13T22:59:29',
       '2021-08-14T03:52:59', '2021-08-14T05:46:14'],
      dtype='datetime64[s]')

In [2]:
class VaryingLengthDataset(Dataset):
    def __init__(self, n, dmin, dmax):
        super().__init__()
        self.size = n
        self.data = [torch.randint(0, 10, (np.random.randint(dmin, dmax), 2)) for _ in range(n)]
        
    # a commemt
    def __len__(self):
        return self.size
    
    def __getitem__(self, index):
        return self.data[index]
    
    def __repr__(self):
        return "".join(repr(x.shape) for x in self.data)
    
def myfun():
    pass

In [137]:
import tsdm

In [ ]:
tsdm.

In [12]:
pandas.Timestamp("2:00")

Timestamp('2021-08-12 02:00:00')

In [129]:
units = { u:np.timedelta64(1, u) for u in ("Y", "M", "W", "D", "h", "m", "s", "us", "ns", "ps", "fs", "as")}
base_unit = next(u for u, val in units.items() if freq >= val)

In [135]:
freq = pandas.Timedelta("15m")

In [136]:


base

'm'

In [90]:
now = pandas.Timestamp("now")
tom = pandas.Timestamp("now") + pandas.Timedelta("24h")


In [91]:
date_range = pandas.date_range(now, tom, freq=Timedelta("17m"))

choice = np.random.default_rng().choice(date_range, size=10, replace=False)

In [96]:
choice

array(['2021-08-13T11:45:48.837710000', '2021-08-14T04:28:48.837710000',
       '2021-08-14T08:09:48.837710000', '2021-08-13T22:48:48.837710000',
       '2021-08-13T23:56:48.837710000', '2021-08-14T08:26:48.837710000',
       '2021-08-13T20:49:48.837710000', '2021-08-13T14:35:48.837710000',
       '2021-08-13T18:16:48.837710000', '2021-08-13T13:10:48.837710000'],
      dtype='datetime64[ns]')

In [103]:
np.datetime64(15, 'm')

TypeError: Cannot convert input [0 days 00:15:00] of type <class 'pandas._libs.tslibs.timedeltas.Timedelta'> to Timestamp

In [105]:
choice.astype(np.datetime64(15, 'm'))

array(['2021-08-13T11:45', '2021-08-14T04:28', '2021-08-14T08:09',
       '2021-08-13T22:48', '2021-08-13T23:56', '2021-08-14T08:26',
       '2021-08-13T20:49', '2021-08-13T14:35', '2021-08-13T18:16',
       '2021-08-13T13:10'], dtype='datetime64[m]')

In [74]:
np.diff(np.sort(choice))

array([ 3060000000000,  9180000000000,  3060000000000, 10200000000000,
        9180000000000,  4080000000000, 12240000000000,  4080000000000,
        4080000000000], dtype='timedelta64[ns]')

In [82]:
import inspect

In [83]:
inspect.getsource(Timestamp)

OSError: source code not available

In [7]:
import numpy

In [2]:
import pandas

In [6]:
type(pandas.Timedelta("1s"))

pandas._libs.tslibs.timedeltas.Timedelta

In [116]:
datetime.datetime?

Init signature: datetime.datetime(self, /, *args, **kwargs)
Docstring:     
datetime(year, month, day[, hour[, minute[, second[, microsecond[,tzinfo]]]]])

The year, month and day arguments are required. tzinfo may be None, or an
instance of a tzinfo subclass. The remaining arguments may be ints.
File:           ~/miniconda3/envs/kiwi/lib/python3.9/datetime.py
Type:           type
Subclasses:     ABCTimestamp, _NaT, real_datetime


In [100]:
import datetime

In [112]:
type(datetime.timedelta(seconds=3))

datetime.timedelta

In [113]:
issubclass(np.timedelta64, datetime.timedelta)

False

In [108]:
np.array(datetime.timedelta(seconds=5), dtype="timedelta64[s]").dtype

dtype('<m8[s]')

In [98]:
dir(np.typing)

['ArrayLike',
 'DTypeLike',
 'NBitBase',
 'NDArray',
 '_128Bit',
 '_16Bit',
 '_256Bit',
 '_32Bit',
 '_64Bit',
 '_80Bit',
 '_8Bit',
 '_96Bit',
 '_ArrayLike',
 '_ArrayLikeBool_co',
 '_ArrayLikeBytes_co',
 '_ArrayLikeComplex_co',
 '_ArrayLikeDT64_co',
 '_ArrayLikeFloat_co',
 '_ArrayLikeInt',
 '_ArrayLikeInt_co',
 '_ArrayLikeNumber_co',
 '_ArrayLikeObject_co',
 '_ArrayLikeStr_co',
 '_ArrayLikeTD64_co',
 '_ArrayLikeUInt_co',
 '_ArrayLikeVoid_co',
 '_BoolCodes',
 '_BoolLike_co',
 '_ByteCodes',
 '_BytesCodes',
 '_CDoubleCodes',
 '_CLongDoubleCodes',
 '_CSingleCodes',
 '_CharLike_co',
 '_Complex128Codes',
 '_Complex64Codes',
 '_ComplexLike_co',
 '_DT64Codes',
 '_DTypeLikeBool',
 '_DTypeLikeBytes',
 '_DTypeLikeComplex',
 '_DTypeLikeComplex_co',
 '_DTypeLikeDT64',
 '_DTypeLikeFloat',
 '_DTypeLikeInt',
 '_DTypeLikeObject',
 '_DTypeLikeStr',
 '_DTypeLikeTD64',
 '_DTypeLikeUInt',
 '_DTypeLikeVoid',
 '_DoubleCodes',
 '_Float16Codes',
 '_Float32Codes',
 '_Float64Codes',
 '_FloatLike_co',
 '_GUFunc_Ni

In [20]:
import xarray


In [21]:
from tsdm.datasets import InSilicoData


In [25]:
dir(InSilicoData)

['__abstractmethods__',
 '__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__slots__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_impl',
 'clean',
 'dataset',
 'dataset_file',
 'dataset_path',
 'download',
 'load',
 'rawdata_path',
 'to_trainloader',
 'url']

In [75]:
dsets = []

for key, val in InSilicoData.dataset.items():
    ds = df.to_xarray()
    ds = ds.assign_coords(run_id = key)
    dsets.append(ds)

In [77]:
dsets

[<xarray.Dataset>
 Dimensions:    (time: 652)
 Coordinates:
   * time       (time) datetime64[ns] 2021-06-28T09:41:57 ... 2021-06-28T21:31:57
     run_id     <U9 'run_16130'
 Data variables:
     Biomass    (time) float64 nan nan nan nan nan nan ... nan nan nan nan nan
     Substrate  (time) float64 nan nan nan nan nan nan ... nan nan nan nan nan
     Acetate    (time) float64 nan nan nan nan nan nan ... nan nan nan nan nan
     DOTm       (time) float64 nan 0.9839 1.0 0.9864 0.9742 ... nan nan nan nan
     Product    (time) float64 nan nan nan nan nan nan ... nan nan nan nan nan
     Volume     (time) float64 0.01 nan nan nan nan ... 0.009797 0.00981 nan nan
     Feed       (time) float64 0.0 0.0 0.0 0.0 ... 2.185e-05 2.185e-05 2.185e-05,
 <xarray.Dataset>
 Dimensions:    (time: 652)
 Coordinates:
   * time       (time) datetime64[ns] 2021-06-28T09:41:57 ... 2021-06-28T21:31:57
     run_id     <U9 'run_16131'
 Data variables:
     Biomass    (time) float64 nan nan nan nan nan nan ... 

In [96]:
np.datetime64?

Init signature: np.datetime64(self, /, *args, **kwargs)
Docstring:     
If created from a 64-bit integer, it represents an offset from
``1970-01-01T00:00:00``.
If created from string, the string can be in ISO 8601 date
or datetime format.

>>> np.datetime64(10, 'Y')
numpy.datetime64('1980')
>>> np.datetime64('1980', 'Y')
numpy.datetime64('1980')   
>>> np.datetime64(10, 'D')
numpy.datetime64('1970-01-11')

See :ref:`arrays.datetime` for more information.

:Character code: ``'M'``
File:           ~/miniconda3/envs/kiwi/lib/python3.9/site-packages/numpy/__init__.py
Type:           type
Subclasses:     


In [91]:
import numpy as np
np.datetime64('now')

numpy.datetime64('2021-08-11T11:01:52')

In [95]:
np.datetime64(24, 'h')

numpy.datetime64('1970-01-02T00','h')

In [84]:
xarray.concat(dsets, dim="run_id").to_dataframe()

Biomass  Substrate  Acetate  DOTm  Product  \
time                run_id                                                  
2021-06-28 09:41:57 run_16130      NaN        NaN      NaN   NaN      NaN   
                    run_16131      NaN        NaN      NaN   NaN      NaN   
                    run_16132      NaN        NaN      NaN   NaN      NaN   
                    run_16133      NaN        NaN      NaN   NaN      NaN   
                    run_16134      NaN        NaN      NaN   NaN      NaN   
...                                ...        ...      ...   ...      ...   
2021-06-28 21:31:57 run_16133      NaN        NaN      NaN   NaN      NaN   
                    run_16134      NaN        NaN      NaN   NaN      NaN   
                    run_16135      NaN        NaN      NaN   NaN      NaN   
                    run_16136      NaN        NaN      NaN   NaN      NaN   
                    run_16137      NaN        NaN      NaN   NaN      NaN   

                               Volume      Feed  
time                run_id                       
2021-06-28 09:41:57 run_16130    0.01  0.000000  
                    run_16131    0.01  0.000000  
                    run_16132    0.01  0.000000  
                    run_16133    0.01  0.000000  
                    run_16134    0.01  0.000000  
...                               ...       ...  
2021-06-28 21:31:57 run_16133     NaN  0.000022  
                    run_16134     NaN  0.000022  
                    run_16135     NaN  0.000022  
                    run_16136     NaN  0.000022  
                    run_16137     NaN  0.000022  

[5216 rows x 7 columns]

In [38]:
arrays = [xarray.DataArray(df, name=key) for key, df in InSilicoData.dataset.items()  ]

In [67]:
arrays[0]

<xarray.DataArray 'run_16130' (time: 652, dim_1: 7)>
array([[           nan,            nan,            nan, ...,
                   nan, 1.00000000e-02, 0.00000000e+00],
       [           nan,            nan,            nan, ...,
                   nan,            nan, 0.00000000e+00],
       [           nan,            nan,            nan, ...,
                   nan,            nan, 0.00000000e+00],
       ...,
       [           nan,            nan,            nan, ...,
                   nan, 9.81012524e-03, 2.18524748e-05],
       [           nan,            nan,            nan, ...,
                   nan,            nan, 2.18524748e-05],
       [           nan,            nan,            nan, ...,
                   nan,            nan, 2.18524748e-05]])
Coordinates:
  * time     (time) datetime64[ns] 2021-06-28T09:41:57 ... 2021-06-28T21:31:57
  * dim_1    (dim_1) object 'Biomass' 'Substrate' 'Acetate' ... 'Volume' 'Feed'

In [40]:
xarray.merge( arrays)

<xarray.Dataset>
Dimensions:    (time: 658, dim_1: 7)
Coordinates:
  * time       (time) datetime64[ns] 2021-06-28T09:41:57 ... 2021-06-28T21:31:57
  * dim_1      (dim_1) object 'Biomass' 'Substrate' ... 'Volume' 'Feed'
Data variables:
    run_16130  (time, dim_1) float64 nan nan nan nan ... nan nan nan 2.185e-05
    run_16131  (time, dim_1) float64 nan nan nan nan ... nan nan nan 2.174e-05
    run_16132  (time, dim_1) float64 nan nan nan nan ... nan nan nan 2.144e-05
    run_16133  (time, dim_1) float64 nan nan nan nan ... nan nan nan 2.144e-05
    run_16134  (time, dim_1) float64 nan nan nan nan ... nan nan nan 2.189e-05
    run_16135  (time, dim_1) float64 nan nan nan nan ... nan nan nan 2.174e-05
    run_16136  (time, dim_1) float64 nan nan nan nan ... nan nan nan 2.281e-05
    run_16137  (time, dim_1) float64 nan nan nan nan ... nan nan nan 2.131e-05

In [50]:
df = list(InSilicoData.dataset.values())[0]
df.name = "agagaga"

In [26]:
xarray.Dataset.from_dict(InSilicoData.dataset)

ValueError: cannot convert dict without the key 'dims'

In [19]:
dir(VaryingLengthDataset)

['__add__',
 '__class__',
 '__class_getitem__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__len__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__orig_bases__',
 '__parameters__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__slots__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_is_protocol']

### Batching this Dataset won't work:

In [3]:
MyDataset = VaryingLengthDataset(100, 3, 7)

try:
    next(iter(DataLoader(MyDataset, batch_size=10)))
    print(x)
except Exception as E:
    print(E)

stack expects each tensor to be equal size, but got [3, 2] at entry 0 and [5, 2] at entry 1


### Let's try with a custom collate_fn

In [4]:
np.random.randint(0, len(MyDataset), 20)

array([33, 23,  6, 29, 94, 44,  0, 21, 52, 36,  8, 14, 77, 84, 45, 74, 84,
       35, 69, 15])

In [5]:
batch = [MyDataset[idx] for idx in np.random.randint(0, len(MyDataset), 5)]
batch

[tensor([[2, 1],
         [5, 7],
         [9, 9],
         [5, 1]]),
 tensor([[1, 1],
         [7, 2],
         [4, 3]]),
 tensor([[2, 0],
         [3, 2],
         [6, 2],
         [1, 1]]),
 tensor([[8, 4],
         [5, 4],
         [8, 2],
         [0, 9],
         [4, 9]]),
 tensor([[1, 0],
         [2, 6],
         [1, 0],
         [0, 3],
         [3, 8]])]

In [6]:
pad_sequence(batch, batch_first=True).shape

torch.Size([5, 5, 2])

In [7]:
def collate_list(batch):
    return batch

try:
    x = next(iter(DataLoader(MyDataset, batch_size=5, collate_fn=collate_list)))
    print(x)
except Exception as E:
    print(E)

[tensor([[6, 5],
        [8, 0],
        [2, 5]]), tensor([[9, 9],
        [9, 1],
        [8, 6],
        [1, 4],
        [7, 0]]), tensor([[3, 6],
        [7, 3],
        [2, 9],
        [5, 3],
        [5, 5],
        [6, 5]]), tensor([[3, 2],
        [2, 5],
        [1, 9],
        [4, 2],
        [1, 7],
        [9, 2]]), tensor([[5, 6],
        [1, 0],
        [5, 5],
        [6, 1],
        [0, 8],
        [2, 0]])]


In [8]:
def collate_packed(batch):
    batch.sort(key=torch.Tensor.__len__, reverse=True)
    return pack_sequence(batch)

try:
    x = next(iter(DataLoader(MyDataset, batch_size=5, collate_fn=collate_packed)))
    print(x)
except Exception as E:
    print(E)

PackedSequence(data=tensor([[3, 6],
        [3, 2],
        [5, 6],
        [9, 9],
        [6, 5],
        [7, 3],
        [2, 5],
        [1, 0],
        [9, 1],
        [8, 0],
        [2, 9],
        [1, 9],
        [5, 5],
        [8, 6],
        [2, 5],
        [5, 3],
        [4, 2],
        [6, 1],
        [1, 4],
        [5, 5],
        [1, 7],
        [0, 8],
        [7, 0],
        [6, 5],
        [9, 2],
        [2, 0]]), batch_sizes=tensor([5, 5, 5, 4, 4, 3]), sorted_indices=None, unsorted_indices=None)


In [9]:
batch = next(iter(DataLoader(MyDataset, batch_size=5, collate_fn=collate_list)))
[x.T for x in batch]

[tensor([[6, 8, 2],
         [5, 0, 5]]),
 tensor([[9, 9, 8, 1, 7],
         [9, 1, 6, 4, 0]]),
 tensor([[3, 7, 2, 5, 5, 6],
         [6, 3, 9, 3, 5, 5]]),
 tensor([[3, 2, 1, 4, 1, 9],
         [2, 5, 9, 2, 7, 2]]),
 tensor([[5, 1, 5, 6, 0, 2],
         [6, 0, 5, 1, 8, 0]])]

In [10]:
batch_sorted = batch.copy()
batch_sorted.sort(key=torch.Tensor.__len__, reverse=True)
[x.T for x in batch_sorted]

[tensor([[3, 7, 2, 5, 5, 6],
         [6, 3, 9, 3, 5, 5]]),
 tensor([[3, 2, 1, 4, 1, 9],
         [2, 5, 9, 2, 7, 2]]),
 tensor([[5, 1, 5, 6, 0, 2],
         [6, 0, 5, 1, 8, 0]]),
 tensor([[9, 9, 8, 1, 7],
         [9, 1, 6, 4, 0]]),
 tensor([[6, 8, 2],
         [5, 0, 5]])]

In [11]:
batch_packed = pack_sequence(batch_sorted)
batch_packed.data.T, batch_packed.batch_sizes

(tensor([[3, 3, 5, 9, 6, 7, 2, 1, 9, 8, 2, 1, 5, 8, 2, 5, 4, 6, 1, 5, 1, 0, 7, 6,
          9, 2],
         [6, 2, 6, 9, 5, 3, 5, 0, 1, 0, 9, 9, 5, 6, 5, 3, 2, 1, 4, 5, 7, 8, 0, 5,
          2, 0]]),
 tensor([5, 5, 5, 4, 4, 3]))

In [12]:
batch_pad_packed, lengths = pad_packed_sequence(batch_packed, batch_first=True)
torch.swapaxes(batch_pad_packed, 1, 2), lengths

(tensor([[[3, 7, 2, 5, 5, 6],
          [6, 3, 9, 3, 5, 5]],
 
         [[3, 2, 1, 4, 1, 9],
          [2, 5, 9, 2, 7, 2]],
 
         [[5, 1, 5, 6, 0, 2],
          [6, 0, 5, 1, 8, 0]],
 
         [[9, 9, 8, 1, 7, 0],
          [9, 1, 6, 4, 0, 0]],
 
         [[6, 8, 2, 0, 0, 0],
          [5, 0, 5, 0, 0, 0]]]),
 tensor([6, 6, 6, 5, 3]))

In [13]:
unpacked_batch = [x[:l].T for x, l in zip(batch_pad_packed, lengths)]
unpacked_batch

[tensor([[3, 7, 2, 5, 5, 6],
         [6, 3, 9, 3, 5, 5]]),
 tensor([[3, 2, 1, 4, 1, 9],
         [2, 5, 9, 2, 7, 2]]),
 tensor([[5, 1, 5, 6, 0, 2],
         [6, 0, 5, 1, 8, 0]]),
 tensor([[9, 9, 8, 1, 7],
         [9, 1, 6, 4, 0]]),
 tensor([[6, 8, 2],
         [5, 0, 5]])]

In [14]:
def reconstruct_batch(packed: PackedSequence) -> list[Tensor]:
    d = packed.data.shape[-1]
    dtype = packed.data.dtype
    device = packed.data.device
    
    lengths = []
    b0 = 0
    for b in batch_sizes:
        
        lengths += [b]

In [15]:
reconstructed_batch = batch_pad_packed
reconstructed_batch

tensor([[[3, 6],
         [7, 3],
         [2, 9],
         [5, 3],
         [5, 5],
         [6, 5]],

        [[3, 2],
         [2, 5],
         [1, 9],
         [4, 2],
         [1, 7],
         [9, 2]],

        [[5, 6],
         [1, 0],
         [5, 5],
         [6, 1],
         [0, 8],
         [2, 0]],

        [[9, 9],
         [9, 1],
         [8, 6],
         [1, 4],
         [7, 0],
         [0, 0]],

        [[6, 5],
         [8, 0],
         [2, 5],
         [0, 0],
         [0, 0],
         [0, 0]]])

In [16]:
batch_pad_packed.shape

torch.Size([5, 6, 2])

In [17]:
def unpack(packed):
    pass

In [18]:
a = MyDataset[:5]
a.sort(key=lambda x: len(x))
a

[tensor([[6, 5],
         [8, 0],
         [2, 5]]),
 tensor([[9, 9],
         [9, 1],
         [8, 6],
         [1, 4],
         [7, 0]]),
 tensor([[3, 6],
         [7, 3],
         [2, 9],
         [5, 3],
         [5, 5],
         [6, 5]]),
 tensor([[3, 2],
         [2, 5],
         [1, 9],
         [4, 2],
         [1, 7],
         [9, 2]]),
 tensor([[5, 6],
         [1, 0],
         [5, 5],
         [6, 1],
         [0, 8],
         [2, 0]])]