In [1]:
import torch
from torch.utils.data import Dataset, DataLoader
import numpy as np
from torch import Tensor
from torch.nn.utils.rnn import pack_sequence, pad_sequence, pack_padded_sequence, pad_packed_sequence, PackedSequence

In [2]:
class VaryingLengthDataset(Dataset):
    def __init__(self, n, dmin, dmax):
        super().__init__()
        self.size = n
        self.data = [torch.randint(0, 10, (np.random.randint(dmin, dmax), 2)) for _ in range(n)]
        
    # a commemt
    def __len__(self):
        return self.size
    
    def __getitem__(self, index):
        return self.data[index]
    
    def __repr__(self):
        return "".join(repr(x.shape) for x in self.data)
    
def myfun():
    pass

### Batching this Dataset won't work:

In [3]:
MyDataset = VaryingLengthDataset(100, 3, 7)

try:
    next(iter(DataLoader(MyDataset, batch_size=10)))
    print(x)
except Exception as E:
    print(E)

stack expects each tensor to be equal size, but got [5, 2] at entry 0 and [4, 2] at entry 1


### Let's try with a custom collate_fn

In [26]:
np.random.randint(0, len(MyDataset), 20)

array([22, 27, 85, 42, 18, 93, 58, 70,  5, 96, 52, 53, 56, 23, 61, 98, 76,
       78, 70, 67])

In [27]:
batch = [MyDataset[idx] for idx in np.random.randint(0, len(MyDataset), 5)]
batch

[tensor([[4, 7],
         [7, 9],
         [7, 8],
         [1, 3]]),
 tensor([[0, 2],
         [0, 9],
         [2, 6],
         [8, 7],
         [9, 6],
         [8, 5]]),
 tensor([[1, 7],
         [3, 8],
         [4, 6],
         [2, 2],
         [8, 1]]),
 tensor([[1, 7],
         [1, 3],
         [3, 6],
         [3, 5]]),
 tensor([[3, 0],
         [2, 3],
         [0, 0],
         [3, 7]])]

In [28]:
pad_sequence(batch, batch_first=True).shape

torch.Size([5, 6, 2])

In [13]:
def collate_list(batch):
    return batch

try:
    x = next(iter(DataLoader(MyDataset, batch_size=5, collate_fn=collate_list)))
    print(x)
except Exception as E:
    print(E)

[tensor([[8, 6],
        [9, 5],
        [4, 8],
        [3, 7],
        [3, 2]]), tensor([[5, 0],
        [6, 9],
        [9, 4],
        [4, 7]]), tensor([[0, 0],
        [8, 8],
        [8, 7],
        [5, 2]]), tensor([[5, 3],
        [0, 9],
        [0, 9],
        [2, 8],
        [8, 2]]), tensor([[1, 4],
        [2, 0],
        [2, 4]])]


In [14]:
def collate_packed(batch):
    batch.sort(key=torch.Tensor.__len__, reverse=True)
    return pack_sequence(batch)

try:
    x = next(iter(DataLoader(MyDataset, batch_size=5, collate_fn=collate_packed)))
    print(x)
except Exception as E:
    print(E)

PackedSequence(data=tensor([[8, 6],
        [5, 3],
        [5, 0],
        [0, 0],
        [1, 4],
        [9, 5],
        [0, 9],
        [6, 9],
        [8, 8],
        [2, 0],
        [4, 8],
        [0, 9],
        [9, 4],
        [8, 7],
        [2, 4],
        [3, 7],
        [2, 8],
        [4, 7],
        [5, 2],
        [3, 2],
        [8, 2]]), batch_sizes=tensor([5, 5, 5, 4, 2]), sorted_indices=None, unsorted_indices=None)


In [15]:
batch = next(iter(DataLoader(MyDataset, batch_size=5, collate_fn=collate_list)))
[x.T for x in batch]

[tensor([[8, 9, 4, 3, 3],
         [6, 5, 8, 7, 2]]),
 tensor([[5, 6, 9, 4],
         [0, 9, 4, 7]]),
 tensor([[0, 8, 8, 5],
         [0, 8, 7, 2]]),
 tensor([[5, 0, 0, 2, 8],
         [3, 9, 9, 8, 2]]),
 tensor([[1, 2, 2],
         [4, 0, 4]])]

In [16]:
batch_sorted = batch.copy()
batch_sorted.sort(key=torch.Tensor.__len__, reverse=True)
[x.T for x in batch_sorted]

[tensor([[8, 9, 4, 3, 3],
         [6, 5, 8, 7, 2]]),
 tensor([[5, 0, 0, 2, 8],
         [3, 9, 9, 8, 2]]),
 tensor([[5, 6, 9, 4],
         [0, 9, 4, 7]]),
 tensor([[0, 8, 8, 5],
         [0, 8, 7, 2]]),
 tensor([[1, 2, 2],
         [4, 0, 4]])]

In [17]:
batch_packed = pack_sequence(batch_sorted)
batch_packed.data.T, batch_packed.batch_sizes

(tensor([[8, 5, 5, 0, 1, 9, 0, 6, 8, 2, 4, 0, 9, 8, 2, 3, 2, 4, 5, 3, 8],
         [6, 3, 0, 0, 4, 5, 9, 9, 8, 0, 8, 9, 4, 7, 4, 7, 8, 7, 2, 2, 2]]),
 tensor([5, 5, 5, 4, 2]))

In [18]:
batch_pad_packed, lengths = pad_packed_sequence(batch_packed, batch_first=True)
torch.swapaxes(batch_pad_packed, 1, 2), lengths

(tensor([[[8, 9, 4, 3, 3],
          [6, 5, 8, 7, 2]],
 
         [[5, 0, 0, 2, 8],
          [3, 9, 9, 8, 2]],
 
         [[5, 6, 9, 4, 0],
          [0, 9, 4, 7, 0]],
 
         [[0, 8, 8, 5, 0],
          [0, 8, 7, 2, 0]],
 
         [[1, 2, 2, 0, 0],
          [4, 0, 4, 0, 0]]]),
 tensor([5, 5, 4, 4, 3]))

In [19]:
unpacked_batch = [x[:l].T for x, l in zip(batch_pad_packed, lengths)]
unpacked_batch

[tensor([[8, 9, 4, 3, 3],
         [6, 5, 8, 7, 2]]),
 tensor([[5, 0, 0, 2, 8],
         [3, 9, 9, 8, 2]]),
 tensor([[5, 6, 9, 4],
         [0, 9, 4, 7]]),
 tensor([[0, 8, 8, 5],
         [0, 8, 7, 2]]),
 tensor([[1, 2, 2],
         [4, 0, 4]])]

In [20]:
def reconstruct_batch(packed: PackedSequence) -> list[Tensor]:
    d = packed.data.shape[-1]
    dtype = packed.data.dtype
    device = packed.data.device
    
    lengths = []
    b0 = 0
    for b in batch_sizes:
        
        lengths += [b]

In [22]:
reconstructed_batch = batch_pad_packed
reconstructed_batch

tensor([[[8, 6],
         [9, 5],
         [4, 8],
         [3, 7],
         [3, 2]],

        [[5, 3],
         [0, 9],
         [0, 9],
         [2, 8],
         [8, 2]],

        [[5, 0],
         [6, 9],
         [9, 4],
         [4, 7],
         [0, 0]],

        [[0, 0],
         [8, 8],
         [8, 7],
         [5, 2],
         [0, 0]],

        [[1, 4],
         [2, 0],
         [2, 4],
         [0, 0],
         [0, 0]]])

In [23]:
batch_pad_packed.shape

torch.Size([5, 5, 2])

In [ ]:
def unpack(packed):
    pass

In [ ]:
a = MyDataset[:5]
a.sort(key=lambda x: len(x))
a