In [1]:
import torch
from torch import Tensor, jit

In [2]:
A =torch.randn(3,4,5)

In [10]:
def _is_float_dtype(x: Tensor) -> bool:
    return x.dtype in (torch.half, torch.float, torch.double, torch.bfloat16,
                       torch.complex32, torch.complex64, torch.complex128)

In [71]:
torch.mean(A, [])

tensor(-0.0733)

In [19]:
@jit.script
def jmean(x: Tensor, dim: list[int] = (), keepdim: bool=False):
    if not _is_float_dtype(x):
        x = x.to(dtype=torch.float)
    return torch.mean(x, dim, keepdim=keepdim)

In [83]:
@jit.script
def torch_scaled_norm(x: Tensor,  p: float = 2, dim: list[int] = (), keepdim: bool = False) -> Tensor:    
    if not _is_float_dtype(x):
        x.to(dtype=torch.float)

    if p == 0:
        # https://math.stackexchange.com/q/282271/99220
        return torch.exp(torch.mean(torch.log(x), dim=dim, keepdim=keepdim))
    if p == 1:
        return torch.mean(x, dim=dim, keepdim=keepdim)
    if p == 2:
        return torch.sqrt(torch.mean(x ** 2, dim=dim, keepdim=keepdim))
    if p == float('inf'):
        return torch.amax(x, dim=dim, keepdim=keepdim)
    # other p
    return torch.mean(x ** p, dim=dim, keepdim=keepdim) ** (1 / p)

In [70]:
torch.tensor([1,2]).to(dtype=torch.bfloat16).dtype == float

False

In [22]:
torch_scaled_norm(torch.tensor([1,2]))

tensor(1.5811)

In [65]:
import numba
from numpy import ndarray
import numpy as np

def numpy_scaled_norm(x: ndarray, p: float = 2, axis = (), keepdims: bool = False) -> ndarray:
    x = np.abs(x)

    if p == 0:
        # https://math.stackexchange.com/q/282271/99220
        return np.exp(np.sum(np.log(x), axis=axis, keepdims=keepdims))
    if p == 1:
        return np.sum(x, axis=axis, keepdims=keepdims)
    if p == 2:
        return np.sqrt(np.sum(x ** 2, axis=axis, keepdims=keepdims))
    if p == np.inf:
        return np.amax(x, axis=axis, keepdims=keepdims)
    # other p
    return np.sum(x**p, axis=axis, keepdims=keepdims) ** (1 / p)

In [66]:
numpy_scaled_norm(np.array([1,2], dtype=np.float32))

array([1., 2.], dtype=float32)

In [51]:
np.array([1,2]).astype(float)

array([1., 2.])

In [72]:
B =np.random.randn(3,4,5)

In [75]:
np.mean(B, axis=())

array([[[ 0.38698914, -0.69870012,  0.72263861, -1.46284918,
         -0.2317452 ],
        [-0.3231808 , -0.00257301, -0.31359833, -0.35588731,
          0.86636796],
        [ 0.6960483 ,  0.87755509,  1.70373643, -0.61264273,
          0.38521942],
        [ 0.10614717, -0.4068801 , -0.40675545,  0.87352798,
         -0.90518702]],

       [[ 0.29261538, -1.13962414, -0.64414601,  2.10608236,
         -0.99283274],
        [ 1.16524192,  2.09274656, -0.00533999, -0.30660114,
          1.22527369],
        [ 1.77306584,  0.45482221, -1.13101581,  0.31339036,
         -1.25111   ],
        [ 0.27053745, -1.51950365, -0.70575619, -0.5967945 ,
         -0.12410686]],

       [[-0.71192362, -1.64200995,  1.41057947,  1.26028392,
         -1.77259807],
        [ 0.47376422, -1.32698678, -0.36486308,  1.76557192,
          1.05677361],
        [-1.56137433,  0.33360709,  0.48170924,  0.10584408,
          0.65178951],
        [-0.67047438, -1.20150862, -0.20072598,  1.30893182,
         -1

In [77]:
list(())

[]