# Title

In [15]:
%config InteractiveShell.ast_node_interactivity='last_expr_or_assign'  # always print last expr.
%config InlineBackend.figure_format = 'svg'
%load_ext autoreload
%autoreload 2
%matplotlib inline

import logging
logging.basicConfig(level=logging.INFO)

In [119]:
logger = logging.getLogger(__name__)

<Logger __main__ (INFO)>

In [123]:
logger.getChild("tada").info("test")

INFO:__main__.tada:test


In [129]:
id(logger)

140321080776976

In [130]:
id(logger.getChild("tada"))

140321003358720

In [127]:
dir(logger)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_cache',
 '_log',
 'addFilter',
 'addHandler',
 'callHandlers',
 'critical',
 'debug',
 'disabled',
 'error',
 'exception',
 'failed',
 'fatal',
 'filter',
 'filters',
 'findCaller',
 'getChild',
 'getEffectiveLevel',
 'handle',
 'handlers',
 'hasHandlers',
 'info',
 'isEnabledFor',
 'level',
 'log',
 'makeRecord',
 'manager',
 'name',
 'parent',
 'passed',
 'propagate',
 'removeFilter',
 'removeHandler',
 'root',
 'setLevel',
 'warn',
 'warning']

In [106]:
import numpy as np
import matplotlib.pyplot as plt

np.set_printoptions(precision=4, floatmode='fixed', suppress=True)
rng = np.random.default_rng()

Generator(PCG64) at 0x7F9F5FA51F20

In [107]:
import logging
import torch
from torch import nn, jit, Tensor
from torch.nn import functional as F
from typing import Final

torch.Size([6])


tensor([0.1350, 0.2347, 0.3192, 0.3633, 0.3719, 0.4431, 0.6196, 0.8244, 0.8632,
        0.9731])

In [ ]:
print(scales.shape)


In [109]:
from tsdm.encoders.modular.torch import Time2Vec, PositionalEncoding

In [118]:
enc = Time2Vec(num_dim, "sin")
display(t)
y = enc(t)
display(y)
enc.inverse(y)

tensor([0.1350, 0.2347, 0.3192, 0.3633, 0.3719, 0.4431, 0.6196, 0.8244, 0.8632,
        0.9731])

tensor([[ 0.1350, -0.6409,  0.9854, -0.1684,  0.4034, -0.8880,  0.6671],
        [ 0.2347, -0.5850,  0.9979, -0.3627,  0.3983, -0.9073,  0.6522],
        [ 0.3192, -0.5353,  0.9997, -0.5161,  0.3939, -0.9222,  0.6394],
        [ 0.3633, -0.5086,  0.9975, -0.5903,  0.3916, -0.9295,  0.6327],
        [ 0.3719, -0.5034,  0.9968, -0.6044,  0.3912, -0.9309,  0.6314],
        [ 0.4431, -0.4591,  0.9878, -0.7126,  0.3875, -0.9418,  0.6204],
        [ 0.6196, -0.3445,  0.9417, -0.9129,  0.3784, -0.9649,  0.5925],
        [ 0.8244, -0.2049,  0.8470, -1.0000,  0.3677, -0.9846,  0.5593],
        [ 0.8632, -0.1778,  0.8243, -0.9973,  0.3657, -0.9874,  0.5529],
        [ 0.9731, -0.1006,  0.7529, -0.9566,  0.3599, -0.9939,  0.5346]],
       grad_fn=<CatBackward0>)

tensor([0.1350, 0.2347, 0.3192, 0.3633, 0.3719, 0.4431, 0.6196, 0.8244, 0.8632,
        0.9731], grad_fn=<SelectBackward0>)

In [112]:
enc.scales

tensor(1.2300)

In [101]:
torch.arange(0, 2*num_dim, 2)

tensor([ 0,  2,  4,  6,  8, 10])

In [102]:
# ... - > ...2d

z = torch.einsum("..., d -> ...d", t, scales)
s = torch.sin(z)
c = torch.cos(z)


out  = torch.cat([s, c], dim=-1)
out.shape
# [(c_, s_) for c_ ,s_ in zip(c, s)]

# c = sum(zip(, torch.cos(z)), ())
# torch.stack(c, dim=0).shape

torch.Size([10, 12])

In [105]:
torch.asin(out[..., 0])

tensor([0.0127, 0.0488, 0.1501, 0.1994, 0.2356, 0.2908, 0.4318, 0.6649, 0.7967,
        0.9199])

In [104]:
s, c = out[..., :num_dim], out[..., num_dim:]


In [97]:
torch.einsum("...d, d -> ...d", torch.asin(s), 1/scales)

tensor([[0.0624, 0.0624, 0.0624, 0.0624, 0.0624, 0.0624],
        [0.0706, 0.0706, 0.0706, 0.0706, 0.0706, 0.0706],
        [0.0938, 0.0938, 0.0938, 0.0938, 0.0938, 0.0938],
        [0.3779, 0.3779, 0.3779, 0.3779, 0.3779, 0.3779],
        [0.4258, 0.4258, 0.4258, 0.4258, 0.4258, 0.4258],
        [0.5054, 0.5054, 0.5054, 0.5054, 0.5054, 0.5054],
        [0.5231, 0.5231, 0.5231, 0.5231, 0.5231, 0.5231],
        [0.5411, 0.5411, 0.5411, 0.5411, 0.5411, 0.5411],
        [0.7689, 0.7689, 0.7689, 0.7689, 0.7689, 0.7689],
        [0.8393, 0.8393, 0.8393, 0.8393, 0.8393, 0.8393]])

In [98]:
t

tensor([0.0624, 0.0706, 0.0938, 0.3779, 0.4258, 0.5054, 0.5231, 0.5411, 0.7689,
        0.8393])

In [78]:
torch.asin(s).shape

torch.Size([10, 10])

In [77]:
scales.shape

torch.Size([6])

In [55]:
s.shape

torch.Size([10, 6])

In [56]:
z.shape

torch.Size([10, 6])

In [48]:
t.shape

c.shape

In [43]:
_.shape

AttributeError: 'str' object has no attribute 'shape'

In [33]:
c.shape

torch.Size([10, 6])

In [11]:
class PositionalEncoding(nn.Module):
    r"""Positional encoding."""

    # Constants
    num_dim: Final[int]
    r"""Number of dimensions."""

    # Buffers
    scale: Tensor
    r"""Scale factor for positional encoding."""
    scales: Tensor
    r"""Scale factors for positional encoding."""

    def __init__(self, num_dim: int, scale: float):
        super().__init__()

        scales = scale ** -torch.arange(0, num_dim+2, 2)/num_dim
        self.register_buffer("scale", torch.tensor(scale), persistent=True)
        self.register_buffer("scales", torch.tensor(scale), persistent=True)

    def forward(self, t: Tensor) -> Tensor:
        r"""Signature: [...] -> [...d].

        Parameters
        ----------
        x: Tensor

        Returns
        -------
        Tensor
        """
        z = torch.einsum("..., d -> ...d", t, self.scales)
        c = sum(zip(torch.sin(z), torch.cos(z)), ())
        return torch.stack(c, dim=-1)

In [13]:
PositionalEncoding(10, 0.01)

PositionalEncoding()